version: "3.3"
services:
  nginx:
    image: jwilder/nginx-proxy
    networks:
      - flowforge 
    restart: always
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
    ports:
      - "80:80"
      # - "443:443"
  postgres:
    image: postgres
    networks: 
      - flowforge
    restart: always
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: root
    volumes:
      - "./db:/var/lib/postgresql/data"
      - "./setup-db.sh:/docker-entrypoint-initdb.d/setup-db.sh"

  flowforge-broker:
    image: "iegomez/mosquitto-go-auth"
    networks:
      - flowforge
    restart: always
    ulimits:
      nofile: 2048
    environment:
      - "VIRTUAL_HOST=mqtt.example.com"
      - "VIRTUAL_PORT=1884"
      - "LETSENCRYPT_HOST=mqtt.example.com"
    volumes:
      - "./broker/mosquitto.conf:/etc/mosquitto/mosquitto.conf"
  forge:
    build:
      context: "./flowforge-docker-local-dev/"
    networks: 
      - flowforge
    restart: always
    environment:
      - "VIRTUAL_HOST=forge.example.com"
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock"
      - "../:/data"
    depends_on:
      - "postgres"
      - "nginx"
  file-server:
    build:
      context: "./file-server"
    image: "flowforge/file-server"
    networks:
      - flowforge
    restart: always
    volumes:
      - "./etc/flowforge-storage.yml:/usr/src/flowforge-file-server/etc/flowforge-storage.yml"
      - "./fileStorage:/usr/src/flowforge-file-server/var/root"
    depends_on:
      - "forge"

networks:
  flowforge: