name: Build and push containers
on: 
  push: 
    tags:
      - "v*.*.*"

jobs:
  build_application_container:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          repository: 'flowforge/docker-compose'
          fetch-depth: 0
          path: 'docker-compose'
      - name: Docker Meta Data
        id: meta
        uses: docker/metadata-action@dc802804100637a589fabce1cb79ff13a1411302 # v6.2.0
        with:
          tags: |
            type=semver,event=tag,pattern={{version}}
          flavor: |
            latest=true
          images: |
            flowforge/forge-docker
            flowfuse/forge-docker
      - name: Setup QEMU
        uses: docker/setup-qemu-action@96fe6ef7f33517b61c61be40b68a1882f3264fb8 # v4.2.0
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@bb05f3f5519dd87d3ba754cc423b652a5edd6d2c # v4.2.0
      - name: docker login
        uses: docker/login-action@af1e73f918a031802d376d3c8bbc3fe56130a9b0 # v4.4.0
        with:
          username: flowforge
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: Build and push FlowForge Application container
        uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a # v7.3.0
        with:
          context: docker-compose/flowforge-docker
          file: docker-compose/flowforge-docker/Dockerfile
          platforms: linux/amd64, linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          push: true
      - name: Push README
        uses: peter-evans/dockerhub-description@1b9a80c056b620d92cedb9d9b5a223409c68ddfa # v5.0.0
        with:
          repository: flowforge/forge-docker
          username: flowforge
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
          readme-filepath: docker-compose/README.md
      - name: Push README flowfuse
        uses: peter-evans/dockerhub-description@1b9a80c056b620d92cedb9d9b5a223409c68ddfa # v5.0.0
        with:
          repository: flowfuse/forge-docker
          username: flowfuse
          password: ${{ secrets.DOCKER_HUB_PASSWORD_FLOWFUSE }}
          readme-filepath: docker-compose/README.md

  release-compose-files:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs: build_application_container
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          repository: 'flowforge/docker-compose'

      - name: Add assets to the release
        uses: softprops/action-gh-release@3d0d9888cb7fd7b750713d6e236d1fcb99157228 # v3.0.2
        with:
          files: |
            docker-compose.yml

  notify-slack:
    name: Notify about release failure
    needs: [build_application_container, release-compose-files]
    if: failure()
    runs-on: ubuntu-latest

    steps:
    - name: Notify Slack
      uses: FlowFuse/github-actions-workflows/actions/slack_notification@slack_notification/v1
      with:
        bot-token: ${{ secrets.SLACK_GHBOT_TOKEN }}
        mode: channel
        blocks: |
          [
            { "type": "header", "text": { "type": "plain_text", "text": ":x: ${{ github.workflow }} workflow failed", "emoji": true } },
            { "type": "divider" },
            { "type": "section", "text": { "type": "mrkdwn", "text": "<${{ github.server_url }}/${{ github.repository }}/actions/workflows/build-containers.yml|${{ github.workflow }}> workflow failed to complete successfully." } },
            { "type": "section", "text": { "type": "mrkdwn", "text": "*Workflow run:*\n<${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|View>" } }
          ]
